/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "image_drawer2.h"

FD_image_drawer *create_form_image_drawer(void)
{
  FL_OBJECT *obj;
  FD_image_drawer *fdui = (FD_image_drawer *) fl_calloc(1, sizeof(*fdui));

  fdui->image_drawer = fl_bgn_form(FL_NO_BOX, 760, 530);
  fdui->background = obj = fl_add_box(FL_UP_BOX,0,0,760,530,"");
  fdui->dashboard_area = obj = fl_add_box(FL_FLAT_BOX,10,55,225,435,"");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_COL1);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
  fdui->closebutton = obj = fl_add_button(FL_NORMAL_BUTTON,9,495,108,27,"Close");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageFormGfx::CB_close,0);
  fdui->savebutton = obj = fl_add_button(FL_NORMAL_BUTTON,122,496,108,27,"Save");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageFormGfx::CB_save,0);

  fdui->coordinates = fl_bgn_group();
  obj = fl_add_text(FL_NORMAL_TEXT,15,95,210,20,"Left mouse zooms out");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_zoomfactor = obj = fl_add_input(FL_FLOAT_INPUT,115,170,100,30,"Zoom Factor = ");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,CoordDashboard::CB_zoomfactor,0);
  fdui->button_showall = obj = fl_add_button(FL_NORMAL_BUTTON,25,231,125,30,"Fit to Window");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,CoordDashboard::CB_center,0);
  fdui->button_redraw = obj = fl_add_button(FL_NORMAL_BUTTON,155,231,60,30,"Redraw");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,CoordDashboard::CB_redraw,0);
  fdui->text_xmin = obj = fl_add_text(FL_NORMAL_TEXT,20,305,170,30,"xmin");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->text_xmax = obj = fl_add_text(FL_NORMAL_TEXT,20,335,170,30,"xmax");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->text_ymin = obj = fl_add_text(FL_NORMAL_TEXT,20,365,170,30,"ymin");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->text_ymax = obj = fl_add_text(FL_NORMAL_TEXT,20,395,170,30,"ymax");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,15,116,210,20,"Middle mouse drags image");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,15,138,210,20,"Right  mouse zooms in");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,16,65,210,20,"Click on the image...");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,15,295,195,140,"Visible Region");
    fl_set_object_color(obj,FL_BLACK,FL_INDIANRED);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_scalefactor = obj = fl_add_input(FL_FLOAT_INPUT,110,445,105,30,"Scale Factor");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,CoordDashboard::CB_input_scalefactor,0);
  fl_end_group();

  fdui->current_dashboard_menu = obj = fl_add_choice(FL_NORMAL_CHOICE,37,15,165,31,"");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageFormGfx::CB_dashboard,0);
  fdui->button_home = obj = fl_add_button(FL_HIDDEN_BUTTON,5,5,35,35,"");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageFormGfx::CB_home,0);

  fdui->display = fl_bgn_group();
  fdui->button_image = obj = fl_add_roundbutton(FL_RADIO_BUTTON,25,80,30,31,"Image");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_image,0);
  fdui->button_material = obj = fl_add_roundbutton(FL_RADIO_BUTTON,25,115,30,31,"Material");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_material,0);
  fdui->button_mesh = obj = fl_add_roundbutton(FL_PUSH_BUTTON,20,220,30,30,"Mesh");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_mesh,0);
  fdui->input_meshwidth = obj = fl_add_input(FL_INT_INPUT,95,220,55,30,"line width");
    fl_set_object_lalign(obj,FL_ALIGN_BOTTOM);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_input_meshwidth,0);
  fdui->button_meshcolor = obj = fl_add_button(FL_NORMAL_BUTTON,155,220,55,30,"Color");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_meshcolor,0);
  fdui->button_selectedpixels = obj = fl_add_roundbutton(FL_PUSH_BUTTON,24,293,30,30,"Pixels");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_selpix,0);
  fdui->button_selectedmesh = obj = fl_add_roundbutton(FL_PUSH_BUTTON,24,323,30,30,"Mesh Triangles");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_selectedmesh,0);
  fdui->button_selpixcolor = obj = fl_add_button(FL_NORMAL_BUTTON,154,293,55,30,"Color");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_pixcolor,0);
  fdui->button_selectedmeshcolor = obj = fl_add_button(FL_NORMAL_BUTTON,154,323,55,30,"Color");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_selectedmeshcolor,0);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,25,285,190,75,"Selected...");
    fl_set_object_color(obj,FL_BLACK,FL_INDIANRED);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_firewalls = obj = fl_add_roundbutton(FL_PUSH_BUTTON,25,380,30,30,"Flrewalls");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_firewalls,0);
  fdui->button_firewallcolor = obj = fl_add_button(FL_NORMAL_BUTTON,155,380,55,30,"Color");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_firewallcolor,0);
  fdui->button_pixmaterial = obj = fl_add_checkbutton(FL_PUSH_BUTTON,60,140,30,30,"show by pixel");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_pixmaterial,0);
  fdui->button_trimaterial = obj = fl_add_checkbutton(FL_PUSH_BUTTON,60,170,30,30,"show by triangle");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_trimaterial,0);
  fdui->button_nomaterialcolor = obj = fl_add_button(FL_NORMAL_BUTTON,155,425,55,30,"Color");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_nomaterialcolor,0);
  obj = fl_add_text(FL_NORMAL_TEXT,45,425,110,30,"Default Material");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fl_end_group();


  fdui->imagemanager = fl_bgn_group();
  fdui->browser_imagelist = obj = fl_add_browser(FL_HOLD_BROWSER,25,85,195,215,"Stored Images");
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
    fl_set_object_callback(obj,ImageManDashboard::CB_browser_imagelist,0);
  fdui->button_store = obj = fl_add_button(FL_NORMAL_BUTTON,60,400,95,30,"Add to list...");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageManDashboard::CB_button_store,0);
  fdui->button_delete = obj = fl_add_button(FL_NORMAL_BUTTON,90,340,65,30,"Delete");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageManDashboard::CB_button_delete,0);
  obj = fl_add_button(FL_RETURN_BUTTON,25,340,65,30,"View");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageManDashboard::CB_button_retrieve,0);
  fdui->button_save_current = obj = fl_add_button(FL_NORMAL_BUTTON,155,400,65,30,"Save...");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageManDashboard::CB_button_save_current,0);
  fdui->button_save_selected = obj = fl_add_button(FL_NORMAL_BUTTON,155,340,65,30,"Save...");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageManDashboard::CB_button_save_selected,0);
  obj = fl_add_text(FL_NORMAL_TEXT,25,310,195,30,"Image selected in list:");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,25,370,195,30,"Currently displayed  image:");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fl_end_group();


  fdui->meshinfo = fl_bgn_group();
  obj = fl_add_box(FL_BORDER_BOX,15,360,215,130,"");
    fl_set_object_color(obj,FL_INDIANRED,FL_BLACK);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->meshinfo_text_Ehomog = obj = fl_add_text(FL_NORMAL_TEXT,15,190,70,30,"E homog.");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_text_Eshape = obj = fl_add_text(FL_NORMAL_TEXT,15,160,70,30,"E shape");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,15,125,45,30,"depth");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,120,125,40,30,"area");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_E_homog = obj = fl_add_text(FL_NORMAL_TEXT,85,190,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_depth = obj = fl_add_text(FL_NORMAL_TEXT,60,125,50,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_area = obj = fl_add_text(FL_NORMAL_TEXT,160,125,65,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_E_shape = obj = fl_add_text(FL_NORMAL_TEXT,85,160,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_size = obj = fl_add_text(FL_NORMAL_TEXT,15,60,210,30,"");
    fl_set_object_color(obj,FL_INACTIVE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_mouse_xy = obj = fl_add_text(FL_NORMAL_TEXT,85,90,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,15,90,55,30,"Mouse");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_text_E = obj = fl_add_text(FL_NORMAL_TEXT,15,220,70,30,"E");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_E = obj = fl_add_text(FL_NORMAL_TEXT,85,220,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->meshinfo_material = obj = fl_add_browser(FL_NORMAL_BROWSER,15,270,105,90,"Material");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
  fdui->meshinfo_groups = obj = fl_add_browser(FL_NORMAL_BROWSER,125,270,105,90,"Groups");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
  fdui->button_meshinfo = obj = fl_add_button(FL_PUSH_BUTTON,130,365,30,30,"?");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_mousemode,0);
    fl_set_button(obj, 1);
  fdui->button_movenode = obj = fl_add_button(FL_PUSH_BUTTON,190,365,30,30,"@-3<->");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_mousemode,0);
  fdui->choice_meshinfo = obj = fl_add_choice(FL_NORMAL_CHOICE,130,395,90,30,"Info for...");
    fl_set_object_boxtype(obj,FL_DOWN_BOX);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_choice_meshinfo,0);
  fdui->meshinfo_text_mouse = obj = fl_add_text(FL_NORMAL_TEXT,25,365,100,30,"Mouse Action:");
    fl_set_object_color(obj,FL_INDIANRED,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->button_highlight = obj = fl_add_checkbutton(FL_PUSH_BUTTON,75,425,30,30,"Clicked");
    fl_set_object_color(obj,FL_COL1,FL_DARKVIOLET);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_button_highlight,0);
  fdui->button_highlight_color = obj = fl_add_button(FL_NORMAL_BUTTON,105,425,60,30,"Color...");
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_button_highlight_color,0);
  fdui->button_meshinfo_selection = obj = fl_add_checkbutton(FL_PUSH_BUTTON,75,455,30,30,"Selected");
    fl_set_object_color(obj,FL_COL1,FL_DARKVIOLET);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_selectedmesh,0);
  fdui->button_meshinfo_selection_color = obj = fl_add_button(FL_NORMAL_BUTTON,105,455,60,30,"Color...");
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,DisplayDashboard::CB_button_selectedmeshcolor,0);
  fdui->button_select_triangle = obj = fl_add_bitmapbutton(FL_NORMAL_BUTTON,160,365,30,30,"");
    fl_set_object_color(obj,FL_COL1,FL_BLACK);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_mousemode,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,165,455,55,30,"Clear");
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,MeshInfoDashboard::CB_button_meshinfo_clearselect,0);
  fl_end_group();

  fdui->image_region = obj = fl_add_box(FL_FLAT_BOX,240,10,510,510,"");
    fl_set_object_color(obj,FL_TOP_BCOL,FL_COL1);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthEast);

  fdui->pixelinfo = fl_bgn_group();
  obj = fl_add_text(FL_NORMAL_TEXT,20,170,70,30,"Color = ");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->info_mouse_xy = obj = fl_add_text(FL_NORMAL_TEXT,90,100,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->info_pixel_xy = obj = fl_add_text(FL_NORMAL_TEXT,90,135,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->info_color = obj = fl_add_text(FL_NORMAL_TEXT,90,170,140,30,"");
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,20,135,55,30,"Pixel");
    fl_set_object_color(obj,FL_INDIANRED,FL_BLACK);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,20,100,55,30,"Mouse");
    fl_set_object_color(obj,FL_INDIANRED,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->browser_material = obj = fl_add_browser(FL_NORMAL_BROWSER,35,230,195,75,"Material");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
  fdui->browser_groups = obj = fl_add_browser(FL_NORMAL_BROWSER,35,330,195,70,"Groups");
    fl_set_object_lalign(obj,FL_ALIGN_TOP_LEFT);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->button_mark = obj = fl_add_checkbutton(FL_PUSH_BUTTON,25,410,30,30,"Mark clicked pixel");
    fl_set_object_color(obj,FL_COL1,FL_GREEN);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,PixelInfoDashboard::CB_button_mark,0);
  fdui->info_image_size = obj = fl_add_text(FL_NORMAL_TEXT,20,65,210,30,"your message here");
    fl_set_object_color(obj,FL_INACTIVE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_infopix_color = obj = fl_add_button(FL_NORMAL_BUTTON,155,410,60,30,"Color...");
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,PixelInfoDashboard::CB_button_infopix_color,0);
  fl_end_group();


  fdui->imagemodification = fl_bgn_group();
  fdui->button_gray = obj = fl_add_button(FL_NORMAL_BUTTON,15,75,125,30,"Gray");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_gray,0);
  fdui->button_smooth = obj = fl_add_button(FL_NORMAL_BUTTON,15,135,125,30,"Smooth");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_smooth,0);
  fdui->button_nonlinear = obj = fl_add_button(FL_NORMAL_BUTTON,15,165,125,30,"Nonlinear Smooth");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_nonlinear,0);
  fdui->button_smooth_params = obj = fl_add_button(FL_NORMAL_BUTTON,140,135,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_smooth_params,0);
  fdui->button_nonlinear_params = obj = fl_add_button(FL_NORMAL_BUTTON,140,165,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_nonlinear_params,0);
  fdui->button_undomod = obj = fl_add_button(FL_NORMAL_BUTTON,20,445,60,30,"Undo");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_undo,0);
  fdui->button_redomod = obj = fl_add_button(FL_NORMAL_BUTTON,155,445,60,30,"Redo");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_redo,0);
  obj = fl_add_box(FL_UP_BOX,140,75,85,30,"");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_undoallmod = obj = fl_add_button(FL_NORMAL_BUTTON,80,445,70,30,"Undo All");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_undoall,0);
  fdui->button_stencil = obj = fl_add_button(FL_NORMAL_BUTTON,15,195,125,30,"Stencil");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_stencil,0);
  fdui->button_stencil_params = obj = fl_add_button(FL_NORMAL_BUTTON,140,195,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_stencil_params,0);
  fdui->button_maxcontrast = obj = fl_add_button(FL_NORMAL_BUTTON,15,105,125,30,"Max Contrast");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_maxcontrast,0);
  obj = fl_add_box(FL_UP_BOX,140,105,85,30,"");
    fl_set_object_lcolor(obj,FL_BOTTOM_BCOL);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_equalize = obj = fl_add_button(FL_NORMAL_BUTTON,15,225,125,30,"Equalize");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_equalize,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,140,225,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,ImageModDashboard::CB_button_equalize_params,0);
  fl_end_group();


  fdui->automation = fl_bgn_group();
  obj = fl_add_text(FL_NORMAL_TEXT,20,155,85,30,"Burn range:");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_text(FL_NORMAL_TEXT,15,210,100,30,"Flammability:");
    fl_set_object_color(obj,FL_SLATEBLUE,FL_MCOL);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,15,285,215,105,"Group B definition");
    fl_set_object_color(obj,FL_BLACK,FL_INDIANRED);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_graingroup = obj = fl_add_input(FL_NORMAL_INPUT,90,70,135,30,"Group A:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_bdygroup = obj = fl_add_input(FL_NORMAL_INPUT,90,100,135,30,"Group B:");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_minburn = obj = fl_add_input(FL_NORMAL_INPUT,120,155,55,30,"min");
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_maxburn = obj = fl_add_input(FL_NORMAL_INPUT,175,155,55,30,"max");
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_local_flam = obj = fl_add_input(FL_INT_INPUT,120,210,55,30,"local");
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_global_flam = obj = fl_add_input(FL_INT_INPUT,175,210,55,30,"global");
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_min_selection = obj = fl_add_input(FL_NORMAL_INPUT,175,245,55,30,"Min selection size:  ");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_max_aspect = obj = fl_add_input(FL_FLOAT_INPUT,170,290,55,30,"Aspect > ");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_max_perimeter = obj = fl_add_input(FL_FLOAT_INPUT,170,325,55,30,"or Perimeter > ");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->input_min_aspect = obj = fl_add_input(FL_FLOAT_INPUT,170,355,55,30,"and Aspect > ");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_verbose = obj = fl_add_checkbutton(FL_PUSH_BUTTON,20,400,30,30,"Verbose?");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->button_auto_redraw = obj = fl_add_checkbutton(FL_PUSH_BUTTON,20,430,30,30,"Redraw?");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->button_go = obj = fl_add_button(FL_NORMAL_BUTTON,165,455,65,30,"GO");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,AutomationDashboard::CB_go,0);
  fl_end_group();


  fdui->selectmethod = fl_bgn_group();
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,20,80,200,340,"");
    fl_set_object_color(obj,FL_BLACK,FL_INDIANRED);
    fl_set_object_lstyle(obj,FL_BOLDITALIC_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_burn = obj = fl_add_checkbutton(FL_RADIO_BUTTON,20,85,30,30,"Burn");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select,SM_BURN);
  fdui->button_rgbburn = obj = fl_add_checkbutton(FL_RADIO_BUTTON,20,115,30,30,"RGB Burn");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select,SM_RGBBURN);
  fdui->button_demography = obj = fl_add_checkbutton(FL_RADIO_BUTTON,20,145,30,30,"Demography");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select,SM_DEMOGRAPHY);
  fdui->button_pixel = obj = fl_add_checkbutton(FL_RADIO_BUTTON,20,175,30,30,"Pixel");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select,SM_PIXEL);
  fdui->button_repeat = obj = fl_add_button(FL_NORMAL_BUTTON,25,225,65,30,"Repeat");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_repeat,0);
  fdui->button_burn_params = obj = fl_add_button(FL_NORMAL_BUTTON,130,85,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_burn_params,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,130,115,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_rgbburn_params,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,130,145,85,30,"Parameters...");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_demography_params,0);
  fdui->button_undo_selection = obj = fl_add_button(FL_NORMAL_BUTTON,135,355,65,30,"Undo");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_undo_selection,0);
  fdui->button_redo_selection = obj = fl_add_button(FL_NORMAL_BUTTON,135,385,65,30,"Redo");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_redo_selection,0);
  fdui->button_select_none = obj = fl_add_button(FL_NORMAL_BUTTON,40,355,65,30,"Clear");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select_none,0);
  fdui->button_select_complement = obj = fl_add_button(FL_NORMAL_BUTTON,40,385,65,30,"Invert");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select_complement,0);
  fdui->input_selectclick = obj = fl_add_input(FL_NORMAL_INPUT,90,225,75,30,"");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_repeat_shifted = obj = fl_add_checkbutton(FL_PUSH_BUTTON,165,230,25,25,"@8->");
    fl_set_object_color(obj,FL_COL1,FL_RED);
    fl_set_object_lalign(obj,FL_ALIGN_RIGHT);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_demograyfy = obj = fl_add_button(FL_NORMAL_BUTTON,25,275,65,30,"Gray...");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_demograyfy,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,25,305,65,30,"RGB..");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_RGB,0);
  fdui->box_pixelparams = obj = fl_add_box(FL_FLAT_BOX,130,175,85,30,"");
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_select_info = obj = fl_add_button(FL_NORMAL_BUTTON,135,440,65,30,"Info");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,SelectDashboard::CB_select_info,0);
  fl_end_group();

  fl_end_form();

  fdui->image_drawer->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_quitform *create_form_quitform(void)
{
  FL_OBJECT *obj;
  FD_quitform *fdui = (FD_quitform *) fl_calloc(1, sizeof(*fdui));

  fdui->quitform = fl_bgn_form(FL_NO_BOX, 310, 130);
  fdui->background = obj = fl_add_box(FL_UP_BOX,0,0,310,130,"");
  fdui->text = obj = fl_add_text(FL_NORMAL_TEXT,60,20,190,40,"Save session before quitting?");
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lalign(obj,FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
  fdui->button_save = obj = fl_add_button(FL_RETURN_BUTTON,10,70,90,30,"Save...");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,QuitForm::CB_quitsave,(long) fdui);
  fdui->button_cancel = obj = fl_add_button(FL_NORMAL_BUTTON,210,70,90,30,"Cancel");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,QuitForm::CB_quitcancel,(long) fdui);
  fdui->button_quitnow = obj = fl_add_button(FL_NORMAL_BUTTON,110,70,90,30,"Don't Save");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_NorthWest);
    fl_set_object_callback(obj,QuitForm::CB_quitnow,(long) fdui);
  fl_end_form();

  fdui->quitform->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

FD_colorbrowser *create_form_colorbrowser(void)
{
  FL_OBJECT *obj;
  FD_colorbrowser *fdui = (FD_colorbrowser *) fl_calloc(1, sizeof(*fdui));

  fdui->colorbrowser = fl_bgn_form(FL_NO_BOX, 140, 330);
  fdui->background = obj = fl_add_box(FL_UP_BOX,0,0,140,330,"");
  fdui->slider_red = obj = fl_add_valslider(FL_VERT_FILL_SLIDER,20,20,30,170,"");
    fl_set_object_color(obj,FL_COL1,FL_RED);
    fl_set_object_lsize(obj,FL_DEFAULT_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
    fl_set_object_callback(obj,ColorBrowser::CB_slider,(long) fdui);
  fdui->slider_grn = obj = fl_add_valslider(FL_VERT_FILL_SLIDER,55,20,30,170,"");
    fl_set_object_color(obj,FL_COL1,FL_GREEN);
    fl_set_object_lsize(obj,FL_DEFAULT_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
    fl_set_object_callback(obj,ColorBrowser::CB_slider,(long) fdui);
  fdui->slider_blu = obj = fl_add_valslider(FL_VERT_FILL_SLIDER,90,20,30,170,"");
    fl_set_object_color(obj,FL_COL1,FL_BLUE);
    fl_set_object_lsize(obj,FL_DEFAULT_SIZE);
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_NorthWest, FL_SouthWest);
    fl_set_object_resize(obj, FL_RESIZE_Y);
    fl_set_object_callback(obj,ColorBrowser::CB_slider,(long) fdui);
  fdui->box_new = obj = fl_add_box(FL_FRAME_BOX,20,195,100,40,"");
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->box_old = obj = fl_add_box(FL_FRAME_BOX,20,240,100,40,"");
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
  fdui->button_ok = obj = fl_add_button(FL_NORMAL_BUTTON,20,290,45,30,"OK");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ColorBrowser::CB_ok,(long) fdui);
  fdui->button_cancel = obj = fl_add_button(FL_NORMAL_BUTTON,70,290,45,30,"Nope");
    fl_set_object_lstyle(obj,FL_BOLD_STYLE);
    fl_set_object_gravity(obj, FL_SouthWest, FL_SouthWest);
    fl_set_object_callback(obj,ColorBrowser::CB_cancel,(long) fdui);
  fl_end_form();

  fdui->colorbrowser->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

